import MasterSection from "../../component/login/masterSection";
import { getTranslations } from "next-intl/server";

export async function generateMetadata({ params }) {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: 'pageTitles' });
  
  return {
    title: t('login'),
    description: "Generated by create next app",
  };
}

function Login() {
  return (
    <>
      <MasterSection />
    </>
  );
}

export default Login;
