import MasterSection from "../../component/login/masterSection";

export const metadata = {
  title: "Login Page",
  description: "Generated by create next app",
};

function Login() {
  return (
    <>
      <MasterSection />
    </>
  );
}

export default Login;
