import MasterSectionPro from "../../component/profile/masterSectionPro";
import { getTranslations } from "next-intl/server";

export async function generateMetadata({ params: { locale } }) {
  const t = await getTranslations({ locale, namespace: 'pageTitles' });
  
  return {
    title: t('profile'),
    description: "Generated by create next app",
  };
}

function Profile() {
  return (
    <>
      <MasterSectionPro />
    </>
  );
}

export default Profile;
