import ProductContainer from "../component/product/productContainer";
export const metadata = {
  title: "Product Page",
  description: "Generated by create next app",
};

async function getProducts() {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/Products/GetAllProductsForUser?pageNumber=1&pageSize=100000`, { cache: "no-store" });
  if (!res.ok) throw new Error(`API Error`);
  const result = await res.json();
  return result.data || [];
}
async function getCategories() {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/Categories/GetAllCategoriesWithoutpagination`, { cache: "no-store" });
  if (!res.ok) throw new Error(`API Error`);
  const results = await res.json();
  return results.data || [];
}

export default async function Product() {
  const products = await getProducts();
  const categoryData = await getCategories();

  return (
    <>

      <ProductContainer products={products} categoryData={categoryData} />
    </>
  );
}
