
import "../styles/globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

import NaviBar from "./component/nav";
import Footer from "./component/footer";


export const metadata = {
  title: "Delicious Sweet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NaviBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
