import { Poppins } from "next/font/google";
import "../styles/globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapClient from "./component/BootstrapClient";
import NaviBar from "./component/nav";
import Footer from "./component/footer";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Choose the weights you need
});

export const metadata = {
  title: "Delicious Sweet",
  description: "Generated by create next app",
  // icons: {
  //   icon: "/assets/images/logo.png", 
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <NaviBar/>
      <BootstrapClient />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
