
import "../styles/globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

import NaviBar from "./component/nav";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NaviBar/>
        {children}
      </body>
    </html>
  );
}
