import MasterSectionRegis from "../../component/register/masterSectionRegis";

export const metadata = {
  title: "Registration Page",
  description: "Generated by create next app",
};

function Registration() {
  return (
    <>
      <MasterSectionRegis />
    </>
  );
}

export default Registration;
