import MasterSectionRegis from "../../component/register/masterSectionRegis";

export const metadata = {
  title: "Registration Page",
  description: "Generated by create next app",
};

async function Registration({params}) {
  const { locale } = await params;
  return (
    <>
      <MasterSectionRegis locale={locale} />
    </>
  );
}

export default Registration;
