import MasterSectionRegis from "../../component/register/masterSectionRegis";
import { getTranslations } from "next-intl/server";

export async function generateMetadata({ params: { locale } }) {
  const t = await getTranslations({ locale, namespace: 'pageTitles' });
  
  return {
    title: t('registration'),
    description: "Generated by create next app",
  };
}

function Registration() {
  return (
    <>
      <MasterSectionRegis />
    </>
  );
}

export default Registration;
