
import SecondSectionC from "../../component/cart/secondSectionC";
import LastPartCart from "../../component/cart/lastPartCart";

export const metadata = {
  title: "Cart Page",
  description: "Generated by create next app",
};
async function Cart() {

  return (
    <>
      <SecondSectionC />
    </>
  );
}

export default Cart;
