import SecondSectionC from "../../component/cart/secondSectionC";
import { getTranslations } from "next-intl/server";

export async function generateMetadata({ params: { locale } }) {
  const t = await getTranslations({ locale, namespace: 'pageTitles' });
  
  return {
    title: t('cart'),
    description: "Generated by create next app",
  };
}

async function Cart({params}) {
  const {locale} = await params;
  return (
    <>
      <SecondSectionC locale={locale} />
    </>
  );
}

export default Cart;
