import SecondSectionP from "../../../component/productDetails/secondSectionP";

export const metadata = {
  title: "Product Details Page",
  description: "Generated by create next app",
};

async function fetchProductDetails(id) {
  try {
    const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/Products/${id}`, {
      cache: "no-store",
    });
    
    if (!res.ok) {
      throw new Error(`Failed to fetch product: ${res.status}`);
    }

    const json = await res.json();
    return {
      data: json.data,
      isError: false
    };
  } catch (error) {
    // console.error("Error fetching product details:", error);
    return {
      data: null,
      isError: true,
      error: error.message
    };
  }
}

export default async function ProductDetails({ params }) {
  const { id } = await params;

  if (!id) {
    return (
      <div className="container py-5 text-center">
        <h3>Invalid product ID</h3>
      </div>
    );
  }

  const productResponse = await fetchProductDetails(id);

  return (
    <div className="product-details-page">
      <SecondSectionP productData={productResponse} />
    </div>
  );
}
