import React from "react";
import ContactUsContainer from "../../component/contactUs/ContactUsContainer";
import "../../../../styles/pagesStyle/contactUs.css";
import { getTranslations } from "next-intl/server";

export async function generateMetadata({ params }) {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "ContactPage" });
  return {
    title: `Delicious Sweet | ${t("HeroSection.header")}`,
    description: "Generated by create next app",
  };
}

export default async function ContactUs() {
  const t = await getTranslations("ContactPage");

  return (
    <div>
      <div className="halfOpcBG pt-md-5">
        <ContactUsContainer />
      </div>
    </div>
  );
}
