import { Poppins } from "next/font/google";
import "../../styles/globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "./component/shared/footer";
import "bootstrap/dist/css/bootstrap.min.css";
import Nav from "./component/shared/nav";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Choose the weights you need
});
export const metadata = {
  title: "Delicious Sweet",
  description: "Generated by create next app",
  // icons: {
  //   icon: "/assets/images/logo.png",
  // },
};

export default async function localeLayout({ children, params }) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  // Providing all messages to the client side
  const messages = await getMessages(); // Pass locale explicitly

  return (
    <html lang={locale || "en"}>
      <body className={`${poppins.variable}`}>
        <NextIntlClientProvider messages={messages}>
          <Nav />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
