import { Poppins } from "next/font/google";
import "../../../styles/globals.css";
import Footer from "../component/shared/footer";
import "bootstrap/dist/css/bootstrap.min.css";
import Nav from "../component/shared/nav";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { AuthProvider } from "@/context/authContext"; 

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Delicious Sweet",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.jpg",
  },
};

export default async function localeLayout({ children, params }) {
  const { locale } = await params;
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale || "en"} dir={locale == "ar" ? "rtl" : "ltr"}>
      <body className={`${poppins.variable}`}>
        <NextIntlClientProvider messages={messages}>
          <AuthProvider>
            <Nav />
            {children}
            <Footer />
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}