import MasterSectionPro from "../component/profile/masterSectionPro";

export const metadata = {
  title: "Profile Page",
  description: "Generated by create next app",
};

function Profile() {
  return (
    <>
      <MasterSectionPro />
    </>
  );
}

export default Profile;
