
import SecondSectionCheck from "../../../component/checkOut/secondSectionCheck";
export const metadata = {
  title: "CheckOut Page",
  description: "Generated by create next app",
};
function CheckOut() {
  return (
    <>
      <SecondSectionCheck />
    </>
  );
}

export default CheckOut;
