import ProductContainer from "../../component/product/productContainer";

export const metadata = {
  title: "Product Page",
  description: "Generated by create next app",
};

async function getCategories() {
  try {
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_API_URL}/Categories/GetAllCategoriesWithoutpagination`,
      { cache: "no-store" }
    );
    if (!res.ok) throw new Error(`API Error: ${res.status}`);
    const results = await res.json();
    return results.data || [];
  } catch (error) {
    return [];
  }
}

export default async function Product({ params, searchParams }) {
  const { locale } = await params;
  const page = (await searchParams?.page) || 1;
  const category = (await searchParams?.category) || null;
  const searchTerm = (await searchParams?.search) || null;

  const catog = await getCategories();

  return (
    <ProductContainer
      locale={locale}
      catog={catog}
      currentCategory={category}
      currentSearch={searchTerm}
      currentPage={page}
    />
  );
}