import React from "react";
import ContactUsContainer from "../component/contactUs/ContactUsContainer";
import "../../../styles/pagesStyle/contactUs.css";
import { getTranslations } from "next-intl/server";

export async function generateMetadata({ params }) {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "ContactPage" });
  return {
    title: `Nuba Nile | ${t("HeroSection.header")}`,
    description: "Generated by create next app",
  };
}
async function getContact() {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_API_URL}/api/contact-data`,
    {
      cache: "no-store", // or 'force-cache', 'reload'
    }
  );
  if (!res.ok) throw new Error("Failed to fetch");
  return res.json();
}

export default async function ContactUs({ params }) {
  const { locale } = await params; // 👈 make sure you get locale from props
  const contactData = await getContact();
  const t = await getTranslations("ContactPage");

  const contactTextData = contactData.data[locale];
  return (
    <div>
      <div className="halfOpcBG pt-md-5">
        <ContactUsContainer contactTextData={contactTextData} />
      </div>
    </div>
  );
}
